# -*- coding: utf-8 -*-
"""Ahorcado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NctB49DpMg4ortrVQB7IvgeUgZ-2ypr7
"""

import random
import os

palabras = ["COMPUTADORA" , "BALONES" , "AUDIFONO", "TECLADO", "ESCRITORIO", "GOLAZO", "NETFLIX","AHORCADO", "BICICLETA", "ATINADO", "TELESCOPIO"]

palabra = list(random.choice(palabras))

horca = ["       !=======|", #cuelga
         "               |", #cabeza 
         "               |", #brazos
         "               |", #cuerpo
         "               |", #piernas
         "_______________|"] #piso

figura = ["      !=======|", #cuelga
         "      :x       |", #cabeza 
         "     / | \     |", #brazos
         "       |       |", #cuerPo
         "      / \      |", #piernas
         "_______________|"] #piso

letras_selecc = []
errores = 1

resultado = []

for i in range(len(palabra)):
  resultado.append("_")

while True:

  os.system("cls")

  print ("AHORCADO")

  for i in range(errores):
    print(figura[i])
  for i in range(len(horca)-errores):
    print(horca[i+errores])

    print()

    print( "    ", end= "  ")
    for i in resultado:
      print(i, end=" ")

    print()
    print()

    if resultado == palabra:
      print("Has ganado")
      break
    
    if errores > 4:
      print("No has adivinado, la palabra es ","".join(palabra))
      print("Game Over")
      break

  while True:
    letra_ingresada_usuario = input("Selecciona una letra: ")
    letra_ingresada = letra_ingresada_usuario.upper()
    if len(letra_ingresada) != 1: #si es distinto 
      print("No es una letra. Ingresa una letra nuevamente: ")
    elif letra_ingresada in letras_selecc:
      print ("Letra repetida. Ingresa otra: ")
    elif  letra_ingresada not in "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ":
      print("No es una letra. Ingresa una letra nuevamente: ")
    else:
      letras_selecc.append(letra_ingresada)
      break

for i in range(len(palabra)):
  if palabra[i] == letra_ingresada:
    resultado[i] = letra_ingresada

  if letra_ingresada not in palabra:
    fallos += 1
  
  print()
  print()